<a href="https://colab.research.google.com/github/lcscezar/Teste-Analista-de-Dados-SX/blob/main/Enem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
### Bibliotecas
import pandas as pd

In [ ]:
### Extração de dados
arquivo = "/content/MICRODADOS_ENEM_2020.csv"
enem = pd.read_csv(arquivo, encoding="ISO-8859-1", sep = ';')

In [10]:
#Filtrando as colunas

enem.columns.values

array(['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC',
       'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA',
       'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH',
       'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA',
       'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC',
       'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1',
       'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5',
       'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006',
       'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014',
       'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'], dtype=object)

In [13]:
### Selecionando as colunas necessárias

DadosEnem = ['NU_INSCRICAO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_COR_RACA',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'TP_ESTADO_CIVIL', 'IN_TREINEIRO', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC',
       'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA',
       'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'NU_NOTA_REDACAO','NU_NOTA_MT',
    'NU_NOTA_CN',
    'NU_NOTA_CH',
    'NU_NOTA_LC',
    'NU_NOTA_REDACAO']

In [14]:
### Atribuindo as legendas aos campos

### Cor/Raça
desc_raca = {
               0 : "Não Declarado",
               1 : "Branco",
               2 : "Preto",
               3:  "Pardo",
               4 : "Amarelo",
               5 : "Indígena"
               }

enem["TP_COR_RACA"] = enem["TP_COR_RACA"].replace(desc_raca)

### Estado Civil
desc_estado_civil = {
               0 : "Não Informado",
               1 : "Solteiro(a)",
               2 : "Casado(a)/Mora com companheiro(a)",
               3:  "Divorciado(a)/Desquitado(a)/Separado(a)",
               4 : "Viúvo(a)"
               }

enem["TP_ESTADO_CIVIL"] = enem["TP_ESTADO_CIVIL"].replace(desc_estado_civil)


### Situação Conclusão
desc_conclusao = {
               1 : "Já concluí o Ensino Médio",
               2 : "Estou cursando e concluirei o Ensino Médio em 2020",
               3 : "Estou cursando e concluirei o Ensino Médio após 2020",
               4 : "Não concluí e não estou cursando o Ensino Médio"
               }

enem["TP_ST_CONCLUSAO"] = enem["TP_ST_CONCLUSAO"].replace(desc_conclusao)


### Tipo de escola do Ensino Médio
desc_escola = {
               1 : "Não Respondeu",
               2 : "Pública",
               3 : "Privada",
               4:  "Exterior"
               }

enem["TP_ESCOLA"] = enem["TP_ESCOLA"].replace(desc_escola)


### Tipo de instituição que concluiu ou concluirá o Ensino Médio
desc_ensino = {
               1 : "Ensino Regular",
               2 : "Educação Especial - Modalidade Substitutiva",
               3:  "Educação de Jovens e Adultos"
               }

enem["TP_ENSINO"] = enem["TP_ENSINO"].replace(desc_ensino)

### Indica se o inscrito fez a prova com intuito de apenas treinar seus conhecimentos
desc_treineiro = {
               1 : "Sim",
               0 : "Não"
               }

enem["IN_TREINEIRO"] = enem["IN_TREINEIRO"].replace(desc_treineiro)

### Dependência administrativa (Escola)
desc_dependencia = {
               1 : "Federal",
               2 : "Estadual",
               3 : "Municipal",
               4 : "Privada"
               }

enem["TP_DEPENDENCIA_ADM_ESC"] = enem["TP_DEPENDENCIA_ADM_ESC"].replace(desc_dependencia)

### Localização (Escola)
desc_localizacao = {
               1 : "Urbana",
               2 : "Rural"
               }

enem["TP_LOCALIZACAO_ESC"] = enem["TP_LOCALIZACAO_ESC"].replace(desc_localizacao)

### Situação de funcionamento (Escola)
desc_situacao = {
               1 : "Em atividade",
               2 : "Paralisada",
               3 : "Extinta",
               4 : "Escola extinta em anos anteriores"
               }

enem["TP_SIT_FUNC_ESC"] = enem["TP_SIT_FUNC_ESC"].replace(desc_situacao)

print(desc_raca)
print(desc_estado_civil)
print(desc_conclusao)
print(desc_escola)
print(desc_ensino)
print(desc_treineiro)
print(desc_dependencia)
print(desc_localizacao)
print(desc_situacao)

{0: 'Não Declarado', 1: 'Branco', 2: 'Preto', 3: 'Pardo', 4: 'Amarelo', 5: 'Indígena'}
{0: 'Não Informado', 1: 'Solteiro(a)', 2: 'Casado(a)/Mora com companheiro(a)', 3: 'Divorciado(a)/Desquitado(a)/Separado(a)', 4: 'Viúvo(a)'}
{1: 'Já concluí o Ensino Médio', 2: 'Estou cursando e concluirei o Ensino Médio em 2020', 3: 'Estou cursando e concluirei o Ensino Médio após 2020', 4: 'Não concluí e não estou cursando o Ensino Médio'}
{1: 'Não Respondeu', 2: 'Pública', 3: 'Privada', 4: 'Exterior'}
{1: 'Ensino Regular', 2: 'Educação Especial - Modalidade Substitutiva', 3: 'Educação de Jovens e Adultos'}
{1: 'Sim', 0: 'Não'}
{1: 'Federal', 2: 'Estadual', 3: 'Municipal', 4: 'Privada'}
{1: 'Urbana', 2: 'Rural'}
{1: 'Em atividade', 2: 'Paralisada', 3: 'Extinta', 4: 'Escola extinta em anos anteriores'}

In [19]:
### Separando as colunas necessárias

EnemDados = enem.filter(DadosEnem)

EnemDados.head(10)

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,...,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_REDACAO,NU_NOTA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_REDACAO
0,200006271946,11,F,Preto,Já concluí o Ensino Médio,11,Não Respondeu,NaN,Não,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,200001195856,11,M,Pardo,Já concluí o Ensino Médio,11,Não Respondeu,NaN,Não,NaN,...,1,1,1,1,580.0,711.3,604.1,661.7,595.3,580.0
2,200001943954,4,F,Pardo,Estou cursando e concluirei o Ensino Médio em ...,0,Pública,Ensino Regular,Não,2927408.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,200001908998,2,M,Pardo,Estou cursando e concluirei o Ensino Médio em ...,0,Pública,Ensino Regular,Não,3547304.0,...,1,1,1,1,760.0,759.4,620.8,675.0,624.2,760.0
4,200001634757,4,F,Pardo,Já concluí o Ensino Médio,1,Não Respondeu,NaN,Não,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,200003132410,3,F,Pardo,Já concluí o Ensino Médio,1,Não Respondeu,NaN,Não,NaN,...,1,1,1,1,700.0,526.7,498.1,604.7,505.4,700.0
6,200001379770,9,M,Pardo,Já concluí o Ensino Médio,6,Não Respondeu,NaN,Não,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,200001334237,4,M,Branco,Já concluí o Ensino Médio,1,Não Respondeu,NaN,Não,NaN,...,1,1,1,1,600.0,753.2,604.6,604.8,562.1,600.0
8,200006762554,5,F,Pardo,Já concluí o Ensino Médio,3,Não Respondeu,NaN,Não,NaN,...,1,1,1,1,600.0,448.5,439.7,383.5,486.2,600.0
9,200005146210,2,M,Preto,Estou cursando e concluirei o Ensino Médio em ...,0,Pública,Ensino Regular,Não,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
### Removendo os valores ausentes da base

EnemDadosIn = EnemDados.dropna()

In [24]:
print(len(EnemDadosIn))
print(len(EnemDados))
print(len(enem))

51021
299071
299071